import { createWriteStream } from "node:fs";
import { resolve } from "node:path";
import archiver from "archiver";
import { getSnapshotByName, getSnapshot } from "./store.js";
import type { Snapshot } from "./types.js";

export interface ExportOptions {
  /** Snapshot name or ID to export */
  name: string;
  /** Output directory for the ZIP file. Defaults to cwd. */
  outDir?: string;
  dbPath?: string;
}

export interface ExportResult {
  zipPath: string;
  snapshot: Snapshot;
}

function findSnapshot(nameOrId: string, dbPath?: string): Snapshot | null {
  return getSnapshotByName(nameOrId, dbPath) ?? getSnapshot(nameOrId, dbPath);
}

function generateReport(snapshot: Snapshot): string {
  const s = snapshot.summary;
  const lines: string[] = [
    `# TokTrace Snapshot Report`,
    ``,
    `## ${snapshot.name}`,
    ``,
    `| Field | Value |`,
    `|-------|-------|`,
    `| ID | \`${snapshot.snapshot_id}\` |`,
    `| Captured | ${snapshot.captured_at} |`,
  ];

  if (snapshot.window_start) {
    lines.push(`| Window | ${snapshot.window_start} → ${snapshot.window_end} |`);
  }
  lines.push(`| Events | ${s.event_count} |`);
  lines.push(``);

  lines.push(`## Token Usage`);
  lines.push(``);
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Input tokens | ${s.total_input_tokens.toLocaleString()} |`);
  lines.push(`| Output tokens | ${s.total_output_tokens.toLocaleString()} |`);
  lines.push(`| Total tokens | ${s.total_tokens.toLocaleString()} |`);
  lines.push(`| Estimated cost | $${s.total_estimated_cost.toFixed(6)} |`);
  lines.push(``);

  if (s.top_spenders.length > 0) {
    lines.push(`## Top Spenders`);
    lines.push(``);
    lines.push(`| Model | Cost | Events |`);
    lines.push(`|-------|------|--------|`);
    for (const sp of s.top_spenders) {
      lines.push(`| ${sp.model} | $${sp.total_cost.toFixed(6)} | ${sp.event_count} |`);
    }
    lines.push(``);
  }

  if (s.suggestions.length > 0) {
    lines.push(`## Suggestions`);
    lines.push(``);
    for (const suggestion of s.suggestions) {
      lines.push(`- ${suggestion}`);
    }
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(`*Generated by TokTrace*`);
  lines.push(``);
  return lines.join("\n");
}

function buildMetadata(snapshot: Snapshot, version: string): Record<string, unknown> {
  return {
    toktrace_version: version,
    capture_timestamp: snapshot.captured_at,
    snapshot_id: snapshot.snapshot_id,
    snapshot_name: snapshot.name,
    exported_at: new Date().toISOString(),
  };
}

export async function exportSnapshot(opts: ExportOptions): Promise<ExportResult> {
  const snapshot = findSnapshot(opts.name, opts.dbPath);
  if (!snapshot) {
    throw new Error(`No snapshot found with name or ID: ${opts.name}`);
  }

  const { default: pkg } = await import("../package.json", { with: { type: "json" } });
  const version = (pkg as { version: string }).version;

  const safeName = snapshot.name.replace(/[^a-zA-Z0-9_-]/g, "_");
  const zipName = `toktrace-${safeName}.zip`;
  const zipPath = resolve(opts.outDir ?? process.cwd(), zipName);

  const snapshotJson = JSON.stringify(snapshot, null, 2);
  const reportMd = generateReport(snapshot);
  const metadataJson = JSON.stringify(buildMetadata(snapshot, version), null, 2);

  await new Promise<void>((resolve, reject) => {
    const output = createWriteStream(zipPath);
    const archive = archiver("zip", { zlib: { level: 9 } });

    output.on("close", resolve);
    archive.on("error", reject);

    archive.pipe(output);
    archive.append(snapshotJson, { name: "snapshot.json" });
    archive.append(reportMd, { name: "report.md" });
    archive.append(metadataJson, { name: "metadata.json" });
    archive.finalize();
  });

  return { zipPath, snapshot };
}
